# Name of the workflow
name: Create MaxTime JRE

# Name of the workflow while running
run-name: Create MaxTime JRE for Java v${{ inputs.javaVersion }} (${{ inputs.runsOn }}) || Issued by @${{ github.actor }}

on:
  # Workflow has to be manually triggered
  workflow_dispatch:
    inputs:
      runsOn:
        description: "What machine should the workflow run on"
        default: "windows-latest"
        required: true
        type: choice
        options:
          - windows-latest
          - ubuntu-latest
          - macos-latest
      javaVersion:
        description: "Which version of Java should the JRE be based off"
        default: "11"
        required: true
        type: string

jobs:
  build-maxtime-jre:
    # Use the specified machine
    runs-on: ${{ inputs.runsOn }}

    steps:
      # Setup Java with specified version
      - uses: actions/setup-java@v4
        with:
          distribution: 'adopt-hotspot'
          java-version: ${{ inputs.javaVersion }}
      
      # Create the JRE with jlink
      - run: jlink --add-modules ALL-MODULE-PATH --no-header-files --no-man-pages --strip-debug --compress=2 --output ./maxtime-jre
      
      # Upload as an artifact
      - uses: actions/upload-artifact@v3
        with:
          name: maxtime-jre-v${{ inputs.javaVersion }}-${{ inputs.runsOn }}
          path: ./maxtime-jre/*
          if-no-files-found: error